version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword  # Certifique-se de que esta senha está correta
      - POSTGRES_DB=testimonial-automation

  redis:
    image: redis:7-alpine
    container_name: redis-testimonial-automation
    ports:
      - 6380:6379
    environment:
      - NODE_ENV=dev
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 10M